import type { Dictionary } from './types';

export const en: Dictionary = {
  nav: {
    home: 'Home',
    useCases: 'Use Cases',
    playground: 'Playground',
    docs: 'Docs',
    try: 'Try',
  },
  hero: {
    headline: 'A DSL that turns LLM output\ninto visual content.',
    sub: 'No rendering pipeline. No template engine. Just structured text that compiles to diagrams, slides, and infographics.',
    cta_playground: 'Try Playground',
    cta_github: 'GitHub',
  },
  problem: {
    title: 'Why Depix?',
    before_title: 'The typical pipeline',
    before_desc: 'JSON schema, template engine, headless browser, screenshot capture — a fragile chain that breaks when the LLM outputs unexpected structure.',
    after_title: 'With Depix',
    after_desc: 'LLM outputs plain text. compile() turns it into a visual. Three steps, zero infrastructure.',
  },
  howItWorks: {
    title: 'Three lines to visual content',
    sub: 'Add the DSL grammar to your system prompt. The LLM outputs Depix DSL. You compile and render.',
    step1: '① Give the LLM the Depix DSL grammar as a system prompt',
    step2: '② The LLM outputs structured DSL text — not JSON, not HTML',
    step3: '③ compile() resolves layout, theme, and coordinates → render',
  },
  examples: {
    title: 'What LLMs generate',
    sub: 'One prompt, one visual. The DSL below was generated by an LLM from a natural language request.',
    prompt_label: 'Prompt',
    dsl_label: 'LLM Output (DSL)',
    result_label: 'Rendered',
    tabs: {
      flowchart: 'Flowchart',
      slides: 'Slide Deck',
      dashboard: 'Dashboard',
      architecture: 'Architecture',
    },
    prompts: {
      flowchart: '"Draw a user signup flow with email verification retry loop."',
      slides: '"Summarize Q3 results in 3 slides."',
      dashboard: '"Create a system monitoring dashboard with key metrics."',
      architecture: '"Draw our microservice architecture — client, API, data layers."',
    },
  },
  integration: {
    title: 'Drop-in integration',
    sub: 'Works wherever JavaScript runs.',
    react_title: 'React Component',
    react_desc: 'Embed diagrams in your app with a single component. No providers, no context — self-contained.',
    markdown_title: 'Markdown / Documents',
    markdown_desc: 'Use depix code blocks in Markdown. Render inline visuals without managing image files.',
    api_title: 'Server-side',
    api_desc: 'compile() runs in Node.js and Edge Runtime. Generate PNG or IR JSON from any backend.',
  },
  footerCta: {
    title: 'Get started',
  },
  useCases: {
    title: 'Use Cases',
    sub: 'Depix fits into different workflows — from markdown documentation to full-blown LLM-powered applications.',
    markdown_title: 'In Markdown',
    markdown_desc: 'Embed diagrams as code blocks in blogs, wikis, and documentation. No image files to manage — the source is text.',
    slides_title: 'As Slides',
    slides_desc: 'Ask an LLM to summarize content into slides. Depix scenes become presentation pages with automatic layout.',
    image_title: 'As Images',
    image_desc: 'Export to PNG for Slack, email, or documents. LLM output → one function call → image file.',
    app_title: 'In Your App',
    app_desc: 'Render diagrams inside your React application. Users see visuals generated in real-time from LLM responses.',
  },
  playground: {
    title: 'Playground',
    placeholder: '// Write Depix DSL here...\n\nflow direction:right {\n  node "Hello" #a\n  node "World" #b\n  #a -> #b\n}',
    error_label: 'Error',
  },
  placeholder: {
    coming_soon: 'Coming soon.',
    back_home: '← Back to Home',
  },
  footer: {
    tagline: 'Declarative visuals from structured text.',
  },
};
